PokemanCardz/Models/Pokemon.cs
namespace PokemonCardz.Models
{
    public class Pokemon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BaseExperience { get; set; }
    }
}

PokemanCardz/Models/PokemonDetails.cs
using Newtonsoft.Json;

namespace PokemonCardz.Repositories
{
    public class PokemonDetails
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("base_experience")]
        public int BaseExperience { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("is_default")]
        public bool IsDefault { get; set; }

        [JsonProperty("order")]
        public int Order { get; set; }

        [JsonProperty("weight")]
        public int Weight { get; set; }

        [JsonProperty("abilities")]
        public object? Abilities { get; set; }

        [JsonProperty("forms")]
        public object? Forms { get; set; }

        [JsonProperty("game_indices")]
        public object? GameIndices { get; set; }

        [JsonProperty("held_items")]
        public object? HeldItems { get; set; }

        [JsonProperty("location_area_encounters")]
        public string? LocationAreaEncounters { get; set; }

        [JsonProperty("moves")]
        public object? Moves { get; set; }

        [JsonProperty("species")]
        public object? Species { get; set; }

        [JsonProperty("sprites")]
        public object? Sprites { get; set; }

        [JsonProperty("stats")]
        public object? Stats { get; set; }

        [JsonProperty("types")]
        public object? Types { get; set; }

        [JsonProperty("past_types")]
        public object? PastTypes { get; set; }
    }
}

PokemanCardz/Models/PokemonResourceList.cs
using Newtonsoft.Json;

namespace PokemonCardz.Repositories
{
    public class PokemonResourceList
    {
        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("next")]
        public string? NextUrl { get; set; }

        [JsonProperty("previous")]
        public string? PreviousUrl { get; set; }

        [JsonProperty("results")]
        public List<PokemonResource> Results { get; set; }
    }

    public class PokemonResource
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }
}

PokemanCardz/Controllers/CardsController.cs
using Microsoft.AspNetCore.Mvc;
using PokemonCardz.Models;
using PokemonCardz.Services;
using X.PagedList;

namespace PokemonCardz.Controllers
{
    public class CardsController : Controller
    {
        private const int PageSize = 10;
        private readonly ILogger<CardsController> _logger;
        private readonly IPokemonDataService _pokemonDataService;

        public CardsController(ILogger<CardsController> logger, IPokemonDataService pokemonDataService)
        {
            _logger = logger;
            _pokemonDataService = pokemonDataService;
        }

        public async Task<ViewResult> IndexAsync(int? page)
        {
            var pokemonList = new List<Pokemon>();
            try
            {
                pokemonList = await _pokemonDataService.GetUsersPokemonAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }
            return View(pokemonList.ToPagedList(page ?? 1, PageSize));
        }
    }
}

PokemanCardz/Views/Cards/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<PokemonCardz.Models.Pokemon>

<head>
  <link rel="stylesheet" href="styles.css">
</head>

<body>
	<div class="text-center">
		<h1 class="display-4">Your cards</h1>
        <h3>(by experience)</h3>
		<div class="container">
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Base Experience
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BaseExperience)
        </td>
    </tr>
}
</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

</body>

PokemanCardz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PokemonCardz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Cards" asp-action="Index">Inventory</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>